[package]
name = "choster"
version = "0.1.0"
authors = ["Oliver Geller <ogeller@u.rochester.edu>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"



[dependencies]
bootloader = "0.9.8"
